name: Magento 2
description: |
  An environment to work on your Magento 2 project.
version: 0.0.1
category: Ecommerce, Web Store
maintainer: "Luderson C Pereira <luderson@howmanyjoins.com>"
license: MIT License
