version: '2'

services:
    web:
        image: ludersonwebjump/nginx:latest
        ports:
            - 80:80
            - 443:443
    php:
        image: ludersonwebjump/php:latest
        user: www-data
