version: '2'

services:
    web:
        image: ludersonwebjump/nginx:latest
        ports:
            - 80:80
            - 443:443
        volumes:
            - /home/${USER}/projects/${PROJECT}/logs/nginx:/var/log/nginx
    php:
        image: ludersonwebjump/php:latest
        user: www-data
        volumes:
            - /home/${USER}/projects/${PROJECT}/logs/php:/var/log/php
            - /home/${USER}/projects/${PROJECT}/src:/var/www/html
